<!--BOOK_INFORMATION-->
<img align="left" style="padding-right:10px;" src="https://www.uv.mx/ffia/files/2012/09/playerLogo2.jpg">

El contenido ha sido adaptado para el curso de Introducción a la ciencia de Datos,
por HTM y GED a partir del libro [Python Data Science Handbook](http://shop.oreilly.com/product/0636920034919.do) 
de Jake VanderPlas y se mantiene la licencia sobre el texto, 
[CC-BY-NC-ND license](https://creativecommons.org/licenses/by-nc-nd/3.0/us/legalcode), 
y sobre el codigo [MIT license](https://opensource.org/licenses/MIT).*

<!--NAVIGATION-->
< [Basicos de NumPy: arreglos](01.02-The-Basics-Of-NumPy-Arrays.ipynb) | [Contenido](Index.ipynb) | [Agregaciones: Min, Max, etc.](01.04-Computation-on-arrays-aggregates.ipynb) >

<a href="https://colab.research.google.com/github/htapia/TallerPythonIntroCienciaDatos/blob/master/notebooks/01.03-Computation-on-arrays-ufuncs.ipynb"><img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" title="Open and Execute in Google Colaboratory"></a>


# Cálculos con Arrays 1. Ufuncs

## Los Loops son Lentooosss

In [32]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [33]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

1 loop, best of 3: 212 ms per loop


## UFuncs

Operaciones *vectorizadas*

In [34]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [35]:
%timeit (1.0 / big_array)

100 loops, best of 3: 3.1 ms per loop


In [36]:
np.arange(5) / np.arange(1, 6)

array([0, 0, 0, 0, 0])

In [37]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

Cálculos usando vectorizacion a través de ufuncs son en general más eficientes que la implementación usando loops

## Exploración de UFuncs

Ufuncs: 
- *unary ufuncs*, operan sobre una sola entrada 
- *binary ufuncs*, operan sobre dos entradas.

### Aritmética de Array 

Las operaciones aritméticas de adición, substracción, multiplicación y división standard:

In [38]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division

('x     =', array([0, 1, 2, 3]))
('x + 5 =', array([5, 6, 7, 8]))
('x - 5 =', array([-5, -4, -3, -2]))
('x * 2 =', array([0, 2, 4, 6]))
('x / 2 =', array([0, 0, 1, 1]))
('x // 2 =', array([0, 0, 1, 1]))


Negation, operador de exponencia ``**`` y operador de módulo ``%``:

In [39]:
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

('-x     = ', array([ 0, -1, -2, -3]))
('x ** 2 = ', array([0, 1, 4, 9]))
('x % 2  = ', array([0, 1, 0, 1]))


Orden standard de las operaciones:

In [40]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

El operador ``+`` es un wrapper para la función ``add``:

In [41]:
np.add(x, 2)

array([2, 3, 4, 5])

The siguiente tabla enlista los operadores aritméticos implementados en NumPy:

| Operator	    | Equivalent ufunc    | Description                           |
|---------------|---------------------|---------------------------------------|
|``+``          |``np.add``           |Addition (e.g., ``1 + 1 = 2``)         |
|``-``          |``np.subtract``      |Subtraction (e.g., ``3 - 2 = 1``)      |
|``-``          |``np.negative``      |Unary negation (e.g., ``-2``)          |
|``*``          |``np.multiply``      |Multiplication (e.g., ``2 * 3 = 6``)   |
|``/``          |``np.divide``        |Division (e.g., ``3 / 2 = 1.5``)       |
|``//``         |``np.floor_divide``  |Floor division (e.g., ``3 // 2 = 1``)  |
|``**``         |``np.power``         |Exponentiation (e.g., ``2 ** 3 = 8``)  |
|``%``          |``np.mod``           |Modulus/remainder (e.g., ``9 % 4 = 1``)|

Adicionalmente, hay operadores Boolean; exploraremos éstos en [Comparaciones, mascaras y logica booleana](01.06-Boolean-Arrays-and-Masks.ipynb).

### Valor Absoluto


In [42]:
# Python abs
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [43]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [44]:
np.abs(x)

array([2, 1, 0, 1, 2])

Esta ufunc puede operar sobre números complejos:

In [45]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

### Funciones Trigonometricas


In [0]:
theta = np.linspace(0, np.pi, 3)

In [47]:
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

('theta      = ', array([0.        , 1.57079633, 3.14159265]))
('sin(theta) = ', array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16]))
('cos(theta) = ', array([ 1.000000e+00,  6.123234e-17, -1.000000e+00]))
('tan(theta) = ', array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16]))


In [48]:
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

('x         = ', [-1, 0, 1])
('arcsin(x) = ', array([-1.57079633,  0.        ,  1.57079633]))
('arccos(x) = ', array([3.14159265, 1.57079633, 0.        ]))
('arctan(x) = ', array([-0.78539816,  0.        ,  0.78539816]))


### Exponentes y Logaritmos


In [49]:
x = [4, 4, 7]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

('x     =', [4, 4, 7])
('e^x   =', array([  54.59815003,   54.59815003, 1096.63315843]))
('2^x   =', array([ 16.,  16., 128.]))
('3^x   =', array([  81,   81, 2187]))


In [50]:
x = [1, 2, 5, 20]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

('x        =', [1, 2, 5, 20])
('ln(x)    =', array([0.        , 0.69314718, 1.60943791, 2.99573227]))
('log2(x)  =', array([0.        , 1.        , 2.32192809, 4.32192809]))
('log10(x) =', array([0.     , 0.30103, 0.69897, 1.30103]))


In [51]:
# for small input
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

('exp(x) - 1 =', array([0.        , 0.0010005 , 0.01005017, 0.10517092]))
('log(1 + x) =', array([0.        , 0.0009995 , 0.00995033, 0.09531018]))


### Ufuncs especializadas


In [0]:
from scipy import special

In [53]:
# Gamma functions (generalized factorials) and related functions
x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2)   =", special.beta(x, 2))

('gamma(x)     =', array([1.0000e+00, 2.4000e+01, 3.6288e+05]))
('ln|gamma(x)| =', array([ 0.        ,  3.17805383, 12.80182748]))
('beta(x, 2)   =', array([0.5       , 0.03333333, 0.00909091]))


In [54]:
# Error function (integral of Gaussian)
# its complement, and its inverse
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x)  =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))

('erf(x)  =', array([0.        , 0.32862676, 0.67780119, 0.84270079]))
('erfc(x) =', array([1.        , 0.67137324, 0.32219881, 0.15729921]))
('erfinv(x) =', array([0.        , 0.27246271, 0.73286908,        inf]))


## Propiedades Avanzadas de Ufunc 


### Especificando la salida

Todas las ufuncs pueden usar el argumento ``out`` para indicar donde asignar el resultado

In [55]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [56]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [0]:
# lo mismo pero crea un array temporal para guardar el resultado de 2**x, 
# seguido de una segunda operacion que copia esos valores a y 
# que puede ser costoso para arrays grandes
y = np.zeros(10)
y[::2] = 2**x

### Agregaciones


In [58]:
x = np.arange(1, 6)
np.add.reduce(x)

15

In [59]:
np.multiply.reduce(x)

120

In [60]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [61]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

Exploraremos un poco mas en [Agregaciones: Min, Max, etc.](01.04-Computation-on-arrays-aggregates.ipynb).

### Productos exteriores


In [62]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

Otros métodos se exploran en [Más índices](01.07-Fancy-Indexing.ipynb),asi como la habilidad de operar entre arrays de distintos tamaños y formas, llamado *broadcasting*, que se ve en [Calculos con Arrays 2. Broadcasting](01.05-Computation-on-arrays-broadcasting.ipynb).

## Ufuncs: Más información

Más información sobre las funciones universales puede consultarse en la documentación de [NumPy](http://www.numpy.org) y [SciPy](http://www.scipy.org).

<!--NAVIGATION-->
< [Basicos de NumPy: arreglos](01.02-The-Basics-Of-NumPy-Arrays.ipynb) | [Contenido](Index.ipynb) | [Agregaciones: Min, Max, etc.](01.04-Computation-on-arrays-aggregates.ipynb) >

<a href="https://colab.research.google.com/github/htapia/TallerPythonIntroCienciaDatos/blob/master/notebooks/01.03-Computation-on-arrays-ufuncs.ipynb"><img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" title="Open and Execute in Google Colaboratory"></a>
